@startuml

'Classes
class Board {
  isCreated : Boolean
  player : Player[]
  field : Field[]
}
class Field {
  name : String
  color : Color
}
abstract class Piece {
  id : Integer
  color : Color
  isTaken : Boolean
  canMove : Boolean
}
class King {
  isCastled : Boolean
}
class Queen
class Bishop
class Knight
class Rook
class Pawn {
  isConverted : Boolean
  isMoved : Boolean
}
class Play {
  gameStatus : String[]
  countdown : Date
  moveRecording : String[[]]
}
class Player {
  color : Color
  playersTurn : Boolean
  name : Name
}
class Move {
  player : Player
  selectedPiece : Piece
  startPos : Field
  endPos : Field
  pieceTaken : Piece
}
class Account {
  id : Integer
  userName : String
  eMail : String
  password : String
  language : String
}
class MovementHandler {
  --
  Boolean validateMove()
}

'Associations



@enduml