@startuml

Player -> Pawn : Spieler wählt Figur aus
Pawn -> MovementHandler : mögliche Züge abfragen
MovementHandler --> Player : Mögliche Zielfelder anzeigen
Player -> Field : Feld auswählen
Field ->> Pawn : Neues Feld zuordnen
Field --> MovementHandler : Spielzug bestätigen

'Mögliche Auswirkungen prüfen

alt hat geschlagen
MovementHandler -> Piece
end

alt wenn noch nicht gezogen
MovementHandler -> Pawn : ist zwei Felder gezogen
end

alt Bauer auf Feld der letzten Reihe
MovementHandler ->> Pawn : ist eingetauscht
MovementHandler -> Player : mögliche Tauschfiguren anzeigen
Player -> Piece : Figur auswählen
Piece --> MovementHandler : gewählte Figur bestätigen 
end
MovementHandler -> Play : Spielstatus updaten
MovementHandler -> Player : Zug abgeschlossen
@enduml